name: GitHub Pages Deploy
on:
  push:
    branches:
      - main
jobs:
  # nsznsznjsz/nsznsznjsz.github.io
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: |
          npm install
          npx lerna bootstrap

      - name: Build
        env:
          BASE_PATH: /
        run: |
          npm run blog:build

      - name: Deploy github page
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: posts/.vuepress/dist
          destination-github-username: nsznsznjsz
          destination-repository-name: nsznsznjsz.github.io
          target-branch: main
          user-email: yuan.zx@outlook.com
          commit-message: |
            Deploy from blog repo, see it for detail

            - repo: github.com/nsznsznjsz/blog
            - commit: github.com/nsznsznjsz/blog/commit/${{ github.sha }}
