name: Copy README
on:
  push:
    branches:
      - main
jobs:
  # nsznsznjsz/nsznsznjsz
  readme-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Copy README to new folder
        env:
          BASE_PATH: /
        run: |
          mkdir .temp
          cp README.md .temp/README.md

      - name: Push README to repository nsznsznjsz/nsznsznjsz
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .temp
          destination-github-username: nsznsznjsz
          destination-repository-name: nsznsznjsz
          target-branch: main
          user-email: yuan.zx@outlook.com
          commit-message: |
            Deploy from blog repo, see it for detail

            - repo: github.com/nsznsznjsz/blog
            - commit: github.com/nsznsznjsz/blog/commit/${{ github.sha }}
