name: Test Blog Build
on:
  push:
    branches:
      - dev
jobs:
  blog-build-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "14"
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build blog site
        env:
          BASE_PATH: /
        run: yarn blog:build
